### ISSUE TITLE
Problem with getting state of device

### ISSUE THREAD

**Issue by glu000** [Aymkdn/tuyacloud-php#14]
First of all thanks for your great work!

I just have one problem with getting the state of a device. The function getDevices uses the 'discovery' request and stores the state of the device. The problem is, that the 'discovery' request can be used only once with 1020 sec. (This time has been increased from 600 sec lately). This means, that it is only possible to get the REAL state of the device every 17 minutes. For my application I need to check the state in real-time (or at least every 5 seconds). Therefore I would need a function which really contacts the device and checks the state.

By the way: in your README, chapter 'usage' there is:

// to get the state of a device
echo "State Switch 1 => ".$tuya->setState([
  "name" => "switch 1"
]);

I think this should be getState instead of setState. Calling setState without value alway turns off the device.

**Comment by Aymkdn** [comment]
Hi,

The limit is fixed by Tuya/SmartLife, and I don't know any other way to get the data from the cloud. It might be possible to locally contact the device the get the state (like a direct connection to the device itself), but it's out of the scope of this project. You may check this [Python project](https://github.com/jasonacox/tinytuya), but it will also depend of your device.

I've updated my code to use 1020 sec instead of 600, and I changed the example from `setState` to `getState` – THANKS!
